In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Crime.csv')
df

/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (1,18) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Incident ID,Offence Code,CR Number,Dispatch Date / Time,NIBRS Code,Victims,Crime Name1,Crime Name2,Crime Name3,Police District Name,...,Street Prefix,Street Name,Street Suffix,Street Type,Start_Date_Time,End_Date_Time,Latitude,Longitude,Police District Number,Location
0,201219928,1204,180063894,12/21/2018 09:13:13 PM,120,1,Crime Against Property,Robbery,ROBBERY - STREET-GUN,WHEATON,...,NaN,GEORGIA,NaN,AVE,12/21/2018 09:13:00 PM,NaN,39.036270,-77.049900,4D,"(39.0363, -77.0499)"
1,201301798,5016,200035833,09/13/2020 12:26:58 AM,90Z,1,Crime Against Society,All Other Offenses,OBSTRUCT GOVT - VIOLATION OF A COURT ORDER,GERMANTOWN,...,NaN,COLTRANE,NaN,DR,08/08/2020 05:10:00 PM,08/08/2020 12:00:00 AM,39.277840,-77.211500,5D,"(39.2778, -77.2115)"
2,201221577,5404,190000342,01/03/2019 02:48:47 AM,90D,1,Crime Against Society,Driving Under the Influence,DRIVING UNDER THE INFLUENCE LIQUOR,ROCKVILLE,...,N,GRANDIN,NaN,AVE,01/03/2019 02:48:00 AM,01/03/2019 02:48:00 AM,39.086688,-77.144754,1D,"(39.0867, -77.1448)"
3,201221577,9053,190000342,01/03/2019 02:48:47 AM,90Z,1,Other,All Other Offenses,LITTERING/TRASH DUMPING,ROCKVILLE,...,N,GRANDIN,NaN,AVE,01/03/2019 02:48:00 AM,01/03/2019 02:48:00 AM,39.086688,-77.144754,1D,"(39.0867, -77.1448)"
4,201294935,2303,200027681,07/16/2020 05:29:50 PM,23C,1,Crime Against Property,Shoplifting,LARCENY - SHOPLIFTING,GERMANTOWN,...,NaN,FREDERICK,NaN,RD,07/16/2020 05:29:00 PM,NaN,39.198295,-77.244900,5D,"(39.1983, -77.2449)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318012,201397682,9199,220046742,10/25/2022 12:00:41 AM,90Z,1,Other,All Other Offenses,POLICE INFORMATION,MONTGOMERY VILLAGE,...,NaN,WOODFIELD,NaN,RD,10/25/2022 12:00:00 AM,NaN,0.000000,0.000000,6D,"(0.0, 0.0)"
318013,201397752,2316,220046795,10/25/2022 10:36:24 AM,23H,1,Crime Against Property,All other Larceny,LARCENY - POSTAL,WHEATON,...,NaN,CONNECTICUT,NaN,AVE,10/25/2022 10:36:00 AM,NaN,39.065940,-77.074800,4D,"(39.0659, -77.0748)"
318014,201397766,2308,220046615,10/24/2022 12:17:38 PM,23D,1,Crime Against Property,Theft from Building,LARCENY - FROM BLDG,SILVER SPRING,...,NaN,HOUSTON,NaN,AVE,10/10/2022 12:17:00 PM,NaN,38.991160,-77.001800,3D,"(38.9912, -77.0018)"
318015,201397789,2610,220046870,10/25/2022 04:49:59 PM,26F,1,Crime Against Property,Identity Theft,IDENTITY THEFT,BETHESDA,...,NaN,FERNWOOD,NaN,CT,10/24/2022 12:00:00 AM,NaN,39.000620,-77.135800,2D,"(39.0006, -77.1358)"
318016,201397815,1303,220046906,10/25/2022 07:37:10 PM,13A,1,Crime Against Person,Aggravated Assault,ASSAULT - AGGRAVATED - FAMILY-STRONG-ARM,WHEATON,...,NaN,GEORGIAN,NaN,WAY,10/25/2022 07:37:00 PM,NaN,39.054410,-77.046200,4D,"(39.0544, -77.0462)"

In [3]:
df = df.drop(columns=['CR Number','Offence Code','NIBRS Code','Dispatch Date / Time','Zip Code', 'Sector','Beat','PRA','Location','Street Prefix','Street Suffix','Address Number','Latitude','Longitude','Block Address','Crime Name3','Crime Name1'], axis=1)
df.head()

,Incident ID,Victims,Crime Name2,Police District Name,City,State,Agency,Place,Street Name,Street Type,Start_Date_Time,End_Date_Time,Police District Number
0,201219928,1,Robbery,WHEATON,SILVER SPRING,MD,MCPD,Street - Bus Stop,GEORGIA,AVE,12/21/2018 09:13:00 PM,NaN,4D
1,201301798,1,All Other Offenses,GERMANTOWN,DAMASCUS,MD,MCPD,Parking Lot - Residential,COLTRANE,DR,08/08/2020 05:10:00 PM,08/08/2020 12:00:00 AM,5D
2,201221577,1,Driving Under the Influence,ROCKVILLE,ROCKVILLE,MD,RCPD,Street - In vehicle,GRANDIN,AVE,01/03/2019 02:48:00 AM,01/03/2019 02:48:00 AM,1D
3,201221577,1,All Other Offenses,ROCKVILLE,ROCKVILLE,MD,RCPD,Street - Other,GRANDIN,AVE,01/03/2019 02:48:00 AM,01/03/2019 02:48:00 AM,1D
4,201294935,1,Shoplifting,GERMANTOWN,GERMANTOWN,MD,MCPD,Retail - Department/Discount Store,FREDERICK,RD,07/16/2020 05:29:00 PM,NaN,5D

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318017 entries, 0 to 318016
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Incident ID             318017 non-null  int64
 1   Victims                 318017 non-null  int64
 2   Crime Name2             317731 non-null  object
 3   Police District Name    317924 non-null  object
 4   City                    316742 non-null  object
 5   State                   318017 non-null  object
 6   Agency                  318017 non-null  object
 7   Place                   318017 non-null  object
 8   Street Name             318016 non-null  object
 9   Street Type             317675 non-null  object
 10  Start_Date_Time         318017 non-null  object
 11  End_Date_Time           149774 non-null  object
 12  Police District Number  318017 non-null  object
dtypes: int64(2), object(11)
memory usage: 31.5+ MB

In [5]:
df.isnull().sum()

Incident ID                    0
Victims                        0
Crime Name2                  286
Police District Name          93
City                        1275
State                          0
Agency                         0
Place                          0
Street Name                    1
Street Type                  342
Start_Date_Time                0
End_Date_Time             168243
Police District Number         0
dtype: int64

In [6]:
df['Agency'].value_counts()

MCPD    274811
GPD      17150
RCPD     17073
TPPD      8349
MCFM       601
MCSO        27
OTHR         4
P            2
Name: Agency, dtype: int64

In [7]:
df['Agency'].unique()

array(['MCPD', 'RCPD', 'GPD', 'TPPD', 'MCFM', 'MCSO', 'OTHR', 'P'],
      dtype=object)

In [8]:
df['State'].value_counts()

MD    317791
16       191
DC        22
VA         4
ME         2
MS         2
ND         1
0          1
MC         1
17         1
15         1
Name: State, dtype: int64

In [9]:
df['Crime Name2'].value_counts()

All Other Offenses                             75407
Theft From Motor Vehicle                       27249
Drug/Narcotic Violations                       23594
Simple Assault                                 21931
Destruction/Damage/Vandalism of Property       19723
Shoplifting                                    16968
Driving Under the Influence                    15240
All other Larceny                              14587
Theft from Building                            11660
Burglary/Breaking and Entering                  9073
Identity Theft                                  9013
Theft of Motor Vehicle Parts or Accessories     7231
Motor Vehicle Theft                             6895
False Pretenses/Swindle/Confidence Game         6700
Liquor Law Violations                           6657
Credit Card/Automatic Teller Machine Fraud      5073
Disorderly Conduct                              5066
Aggravated Assault                              4529
Trespass of Real Property                       4015
Robbery                                         3715
Runaway                                         3707
Counterfeiting/Forgery                          3323
Weapon Law Violations                           2381
Drug Equipment Violations                       2013
Impersonation                                   1608
Forcible Rape                                   1439
Fondling                                        1164
Family Offenses, NonViolent                      800
Pocket/picking                                   713
Forcible Sodomy                                  615
Forcible Fondling                                563
Embezzlement                                     484
Intimidation                                     437
Purse-snatching                                  417
Sexual Assault With An Object                    412
Extortion/Blackmail                              406
Arson                                            364
Bad Checks                                       343
Pornography/Obscene Material                     310
Wire Fraud                                       288
NOT NIBRS CODE                                   278
Not Mapped                                       271
Stolen Property Offenses                         229
Prostitution                                     184
Murder and Nonnegligent Manslaughter             121
Peeping Tom                                      114
Drunkenness                                      109
Kidnapping/Abduction                              76
From Coin/Operated Machine or Device              57
Human Trafficking, Commercial Sex Acts            47
Statuory Rape                                     35
Curfew/Loitering/Vagrancy Violations              34
Assisting or Promoting Prostitution               22
Welfare Fraud                                     22
Justifiable Homicide                              13
Negligent Manslaughter                             2
Human Trafficking, Involuntary Servitude           2
Operating/Promoting/Assisting Gambling             1
Bribery                                            1
Name: Crime Name2, dtype: int64